name: CI
on:
  push:
    branches: ['master'] # forall push/merge in master
  pull_request:
    branches: ['**']  # forall submitted Pull Requests
jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run docker-coq-action
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'dummy.opam'
          custom_image: ${{ matrix.image }}
          custom_script: |
            set -o pipefail
            pwd
            ls -l
            sudo chown -v coq:coq .  # Workaround a permission issue:
            # the container user has UID=GID=1000,
            # while the GHA workdir has (UID=1001, GID=116).
            # this issue does not occur when using opam; only in this use case.
            mkdir artifacts
            opam list > artifacts/deps.txt
            coqc test.v 2>&1 | tee artifacts/artifact.txt
            curl --version
            sudo chown -v 1001:116 .  # Revert the permissions back
      - name: Display artifacts
        run: |
          set -x
          ls -l
          cd artifacts
          cat deps.txt
          cat artifact.txt
